writers/urls.py
# coding: utf8
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
admin.autodiscover()
from django.conf.urls import include, url
from main_app.views import ListJobs, Performers, CloseReport, Sallary, AddSallary
from main_app.ajax import xhr_test

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', ListJobs.as_view()),
    url(r'^close_report/(?P<pk>\d{1,9})/$', CloseReport.as_view()),
    url(r'^close_report_save/(?P<pk>\d{1,9})/$', CloseReport.as_view()),
    url(r'^performers/$',  Performers.as_view()),
    url(r'^performers/(?P<type_performer>\w+)/$', Performers.as_view()),
    url(r'^sallary/$',  Sallary.as_view()),
    url(r'^sallary/(?P<type_performer>\w+)/$', Sallary.as_view()),
    url(r'^create_sallary/$', AddSallary.as_view()),
    url(r'^create_sallary_save/$', AddSallary.as_view()),
    url(r'^accounts/login/',
        'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$',
        'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^xhr_test/$', xhr_test),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_ROOT,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

writers/main_app/models.py
# coding: utf8
from django.db import models


class JobTitle(models.Model):
    '''Проекты'''
    name = models.CharField(unique=True, max_length=150,
                            help_text=u'проект nashbutik.ru, копирайтинг',
                            verbose_name=u'Проекты')
    date_execution = models.DateTimeField(verbose_name=u'Дата начала работы')
    wage_rate = models.PositiveIntegerField(blank=True, null=True,
                                       verbose_name=u'Ставка за единицу',
                                       help_text=u'цена оплаты за \
                                       одну статью или 1000 символов',
                                       )
    performers = models.ManyToManyField('myuser.UserProfile',
                                        help_text=u'Фамилии исполнителей',
                                        verbose_name=u'Исполнители',
                                        blank=True)
    note = models.CharField(null=True, blank=True, max_length=255,
                            verbose_name='Примечание')
    object_delete = models.BooleanField(verbose_name=u'Отметка об удалении',
                                        default=False)

    class Meta:
        verbose_name = u'Названия проектов'
        verbose_name_plural = u' Названия проектов'
        ordering = ['name']
        db_table = 'jobtitle'
        permissions = (('perms_job_title', u'права на название проектов'),)

    def __unicode__(self):
        return u'%s' % self.name


class Wages(models.Model):
    '''Зарплата'''
    performer_sallary = models.ForeignKey('myuser.UserProfile',
                                          verbose_name='Сотрудник')
    date = models.DateTimeField(verbose_name=u'Дата')
    name_job = models.ForeignKey(JobTitle, to_field='name',
                                 verbose_name='Наименование проекта')
    cost = models.PositiveIntegerField(blank=True, null=True,
                                       verbose_name=u'Ставка в (грн.)')
    number_position = models.PositiveIntegerField(blank=True, null=True,
                                                  verbose_name=u'Кол-во \
                                                  сделанных статей')
    wage = models.PositiveIntegerField(blank=True, null=True,
                                       verbose_name=u'Сумма з/п')
    note = models.CharField(blank=True, null=True,
                            max_length=255, verbose_name=u'Примечание')
    object_delete = models.BooleanField(default=False,
                                        verbose_name=u'Отметка об удалении')

    class Meta:
        verbose_name = u'Зарплата'
        verbose_name_plural = u'Зарплата'
        ordering = ['-date']
        db_table = 'wages'
        permissions = (('perms_sallary', u'права на зарплату'),)

    def __unicode__(self):
        return u'%s' % self.performer_sallary


class ReportUsers(models.Model):
    '''Отчеты'''
    performer = models.ForeignKey('myuser.UserProfile',
                                  verbose_name='Исполнитель')
    date_report = models.DateTimeField(verbose_name=u'Дата создания отчета')
    name_job = models.ForeignKey(JobTitle, to_field='name',
                                 verbose_name='Наименование работы')
    url = models.URLField(max_length=255, blank=True, null=True,
                          verbose_name=u'Ссылка на отчет в GoogleDocs')
    number_symbols = models.PositiveIntegerField(blank=True, null=True,
                                                 verbose_name=u'Количество \
                                                  напечатанных символов')
    note = models.CharField(blank=True, null=True,
                            max_length=255, verbose_name=u'Прим.')
    signature_accept = models.BooleanField(verbose_name="Отметка о проверке \
                                           отчета", default=False)
    object_delete = models.BooleanField(default=False,
                                        verbose_name=u'Отметка об удалении')

    class Meta:
        verbose_name = u'Отчеты'
        verbose_name_plural = u'Отчеты'
        ordering = ['-date_report']
        db_table = 'reportusers'
        permissions = (('perms_url', u'права на отчеты'),)

    def __unicode__(self):
        return u'%s' % self.url

writers/myuser/models.py
# coding: utf8
from django.contrib.auth.models import AbstractUser
from django.db import models

AbstractUser._meta.get_field('email')._unique = True
AbstractUser._meta.get_field('email').blank = False

sort_performer = (('freelancer', u'Фрилансер'), ('office', u'Офис'))


class Position(models.Model):
    '''Наименование должностей'''
    name_position = models.CharField(blank=True, null=True, max_length=150,
                                     verbose_name=u'Название должности')

    class Meta:
        verbose_name = 'Наименование должностей'
        verbose_name_plural = 'Наименование должностей'
        ordering = ['name_position']
        permissions = (('perms_position', 'права на должности'),)

    def __unicode__(self):
        return u'%s' % self.name_position


class UserProfile(AbstractUser):
    skype = models.CharField(blank=True, max_length=255,
                             verbose_name=u'Имя в skype')
    number_cart = models.CharField(blank=True, max_length=255,
                                   verbose_name=u'Номер зарплатной карты')
    type_performer = models.CharField(choices=sort_performer, max_length=100,
                                      verbose_name='Тип сотрудника')
    position = models.ForeignKey(Position, blank=True, null=True,
                                 verbose_name=u'Должность сотрудника')

    class Meta:
            verbose_name = 'Сотрудники'
            verbose_name_plural = 'Сотрудники'
            ordering = ['username']
            permissions = (('perms_userprofile',
                            u'права на редактирование сотрудников'),)

    def __unicode__(self):
        return u'%s %s' % (self.first_name,
                           self.last_name)

    def get_full_name(self):
        return u'%s %s' % (self.first_name, self.last_name,)

    def get_short_name(self):
        return u'%s' % self.username

writers/main_app/forms.py
# coding: utf8
from django import forms
from datetime import *
from django.forms import ModelForm
from .models import Wages
import autocomplete_light


class FormsAddWages(ModelForm):
    '''Форма модели для замены техники'''
    def __init__(self, *args, **kwargs):
        super(FormsAddWages, self).__init__(*args, **kwargs)
        self.fields['cost'].widget=forms.TextInput(attrs={'oninput':'calculate()'})
        self.fields['number_position'].widget=forms.TextInput(attrs={'oninput':'calculate()'})
        self.fields['date'].initial = datetime.now()
        self.fields['wage'].widget.attrs['readonly'] = True
        self.fields['cost'].required = True
        self.fields['number_position'].required = True

    class Meta:
        #~ widgets = {
            #~ 'previous_department': autocomplete_light.ChoiceWidget('DepartmentAutocomplete', attrs={'size':'40'}),
            #~ 'next_department': autocomplete_light.ChoiceWidget('DepartmentAutocomplete', attrs={'size':'40'}),
            #~ 'name_device': autocomplete_light.ChoiceWidget('DeviceAutocomplete', attrs={'size':'40'}),
        #~ }
        model = Wages
        fields = "__all__"

writers/myuser/forms.py
# coding: utf8
from models import UserProfile
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm


# Допиливаем форму добавления пользователя.
# В Meta.model указываем нашу модель.
class AdminUserAddForm(UserCreationForm):

    class Meta:
        model = UserProfile
        fields = ("username", "email", "password1", "password2")

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            UserProfile._default_manager.get(username=username)
        except UserProfile.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])


# Допиливаем форму редактирования пользователя.
# В Meta.model указываем нашу модель.
class AdminUserChangeForm(UserChangeForm):

    class Meta:
        model = UserProfile
        fields = "__all__"

writers/main_app/views.py
# coding: utf8
from .models import JobTitle, ReportUsers, Wages
from .forms import FormsAddWages
from django.views.generic import ListView, DetailView, CreateView
from writers.myuser.models import UserProfile
from django.http import HttpResponseRedirect
from django.http import Http404


class ListJobs(ListView):
    model = JobTitle
    template_name = 'base.html'

    def get_context_data(self, **kwargs):
        context_data = super(ListJobs, self).get_context_data(**kwargs)
        staff_report = ReportUsers.objects.all()
        context_data['staff_report'] = staff_report
        return context_data


class AddSallary(CreateView):
    model = Wages
    form_class = FormsAddWages
    template_name = 'create_sallary.html'
    success_url = '/sallary/'
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class Sallary(ListView):
    model = Wages
    template_name = 'sallary.html'
    context_object_name = 'sallary_performers'

    def get(self, request, *args, **kwargs):
        qkwargs = {}
        for key in ['type_performer']:
            if kwargs.has_key(key):
                qkwargs[key] = kwargs[key]
        self.queryset = Wages.objects.all()
        print kwargs
        if kwargs.has_key('type_performer'):
            if kwargs['type_performer']==u'freelancer':
                self.type = 'Фрилансеры'
                self.queryset = Wages.objects.filter(performer_sallary__type_performer='freelancer')
        if kwargs.has_key('type_performer'):
            if kwargs['type_performer']==u'office':
                self.type = 'Офисные сотрудники'
                self.queryset = Wages.objects.filter(performer_sallary__type_performer='office')
        try:
            self.performer = '%s' % (
                getattr(self, 'type', 'Все сотрудники'),
            )
        except:
            pass
        return super(Sallary, self).get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context_data = super(Sallary, self).get_context_data(**kwargs)
        context_data['performer'] = self.performer
        return context_data


class Performers(ListView):
    model = UserProfile
    template_name = 'performers.html'
    context_object_name = 'list_performers'

    def get(self, request, *args, **kwargs):
        qkwargs = {}
        for key in ['type_performer']:
            if kwargs.has_key(key):
                qkwargs[key] = kwargs[key]
        self.queryset = self.model.objects.filter(**qkwargs)
        print kwargs
        if kwargs.has_key('type_performer'):
            if kwargs['type_performer']==u'freelancer':
                self.type = 'Фрилансеры'
        if kwargs.has_key('type_performer'):
            if kwargs['type_performer']==u'office':
                self.type = 'Офисные сотрудники'
        try:
            self.performer = '%s' % (
                getattr(self, 'type', 'Все сотрудники'),
            )
        except:
            pass
        return super(Performers, self).get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context_data = super(Performers, self).get_context_data(**kwargs)
        context_data['performer'] = self.performer
        return context_data


class CloseReport(DetailView):
    # закрыть отчет
    model = ReportUsers
    template_name = 'close_report.html'
    
    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        if request.user.is_superuser:
            return super(CloseReport, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect('/')
    
    def post(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            obj = self.get_object()
            get_referer = request.META.get('HTTP_REFERER')
            obj.signature_accept = True
            obj.save()
            if get_referer != None:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            if get_referer == None:
                return HttpResponseRedirect('/')
            # return HttpResponseRedirect(self.get_success_url())
        else:
            raise Http404

writers/myuser/views.py
# -*- coding: utf-8 -*-

writers/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
        {% block title %}
            <title>{{title}}</title>
        {% endblock %}

        {% load staticfiles %}

        {% block base_css %}
            <!-- Bootstrap core CSS -->
            <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
            <link href="{% static 'css/custom.css' %}" rel="stylesheet">
            <link href="{% static 'bootstrap/css/sticky-footer-navbar.css' %}" rel="stylesheet">
            <style>
            html, body {
            height: 100%;
            }
            footer {
            color: #666;
            background: #222;
            padding: 17px 0 18px 0;
            border-top: 1px solid #000;
            }
            footer a {
            color: #999;
            align:right;
            }
            footer a:hover {
            color: #efefef;
            }
            .wrapper {
            min-height: 100%;
            height: auto !important;
            height: 100%;
            margin: 0 auto -63px;
            }
            .hero-unit {
            margin-left:20px;
            margin-right:20px;
            padding:10px;
            }
            .push {
            height: 63px;
            }
            /* not required for sticky footer; just pushes hero down a bit */
            .wrapper > .container1 {
            padding-top: 60px;
            }
        </style>
        {% endblock %}

        {% block base_script %}
            <!-- Core JavaScript -->
            <script src="{% static 'jquery/jquery-1.10.2.min.js' %}"></script>
            <script src="{% static 'js/destroy_modal.js' %}"></script>
            <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        {% endblock %}

        {% block custom_css %}
             <!-- Custom styles for this template -->
        {% endblock %}

        {% block custom_script %}
        {% endblock %}
  </head>

  <body>
      
        {% block head_menu %}
<div class="no-print">
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            
            <a class="navbar-brand" href="/">{{title}}</a>
          </div>
          <div class="collapse navbar-collapse">
            
            {% if user.is_authenticated %}
                <p class="navbar-text navbar-right">
                Вы вошли как <a href="#" class="navbar-link">{{ request.user.get_full_name }}</a>
                </p>
                <p class="navbar-text navbar-right">
                <a href="/accounts/logout/" class="navbar-link">Выйти</a>
                </p>
                
            {% else %}
            <form class="navbar-form navbar-right" action='/accounts/login/' method='post'>{% csrf_token %}
                <div class="form-group">
                <input type="text" placeholder="Логин" class="form-control" name="username" value="" id="username">
                </div>
                <div class="form-group">
                <input type="password" placeholder="Пароль" class="form-control" name="password" value="" id="password">
                </div>
                <input type="submit" class="btn btn-primary" value="Войти" />
                <input type="hidden" name="next" value="{{request.path}}" />
            </form>
            {% endif %}
            
          </div><!--/.nav-collapse -->
        </div>
      </div>
</div>
        {% endblock %}
    
    <div class="wrapper">
        <div class="container1">
            <header class="hero-unit">
               {% if user.is_authenticated %}
               <div class="row">
        <div class="col-sm-3 col-md-3">
            {% block sidebar %}
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-folder-close">
                            </span> Раздел администраторов</a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-cog text-primary"></span><a href="/admin/"> Администрирование</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-pencil text-primary"></span><a href="#"> Добавить новый вид работы</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-list-alt text-primary"></span><a href="#"> Cписок всех видов работ</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-flash text-success"></span><a href="/sallary/"> Зарплата</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-file text-info"></span><a href="#"> Архив отчетов</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-user"></span><a href="/performers/"> Сотрудники</a>
                                        <span class="badge">{{staff|length}}</span>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <hr>
                 <!-- Begin cycle-->
                {% for obj in jobs %} 
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree{{ obj.id }}"><span class="glyphicon glyphicon-user">
                            </span> {{ obj }}</a>
                        </h4>
                    </div>
                    <div id="collapseThree{{ obj.id }}" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        {% for item in obj.performers.all %}<a href="#"><strong>{{ item }}</strong><br></a>{% endfor %}
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <!-- End cycle -->
            </div>
        </div>
        {% endblock %} <!-- End sidebar -->
        
        <div class="col-sm-9 col-md-9">
            {% block content %}
                <h2>Отчеты сотрудников</h2>
                <table class="table table-responsive">
                    <thead>
                        <tr>
                            <th>Дата создания отчета</th>
                            <th>Исполнитель</th>
                            <th>Наименование работы</th>
                            <th>Ссылка на отчет в GoogleDocs</th>
                            <th>Количество напечатанных символов</th>
                            <th>Статус отчета</th>
                            <th>Прим.</th>
                        </tr>
                    </thead>
                    {% for obj in staff_report %}
                    <tbody>
                        <tr>
                            <td>{{ obj.date_report|date:"j.m.Y H:i"}}</td>
                            <td><a href="#"><strong>{{ obj.performer }}</strong></a></td>
                            <td>{{ obj.name_job.name }}</td>
                            <td><a href="#">{{ obj.url }}</a></td>
                            <td>{% if obj.number_symbols == None %}
                                <p> - </p>
                                {% else %}
                                <p>{{ obj.number_symbols }}</p>
                                {% endif %}
                            </td>
                            {% if obj.signature_accept == False %}
                                <td class = "danger">Не проверен
                                </br>
                                <!-- Button trigger modal -->
                                <a href="/close_report/{{obj.pk}}/" class="btn btn-default btn-xs" data-toggle="modal" data-target="#myModal">
                                Закрыть отчет <span class="glyphicon glyphicon-ok-sign"></span>
                                </a>
                                <!-- Modal -->
                                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                </div><!-- /.modal -->
                                {% else %}
                                </td>
                                <td class = "success">Проверен</td>
                                {% endif %}
                            <td><a href="#">{{ obj.note }}</a></td>
                        </tr>
                    </tbody>
                    {% endfor %}
                </table>
        </div>
        {% endblock %}
    </div>
        </header>
             {% else %}
            <h2>Вы не авторизованы :(</h2>
            {% endif %}
        </div><!--end container-->

        <div class="push"><!--//--></div>
    </div><!--end wrapper-->
    
    {% block footer %}
    <div class="no-print">
       <div id="footer">
          <div class="container">
            <p class="text-muted credit">Powered by Django</p>
          </div>
        </div>
    </div>
    {% endblock %}
    </body>
      
  </body>
</html>

writers/templates/close_report.html
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Изменение статуса отчета для оформления зарплаты</h4>
      </div>
      <div class="modal-body">
        
        {% block content %}

        <p>Изменить статус отчета от {{object.date_report}} сотрудника <strong>{{object.performer}}</strong></p>
        <p>касающийся проекта <strong>{{object.name_job}}</strong></br>
        <strong>{{object.name_cart.number_cartridge}}</strong></p>
        <div class="alert alert-warning">Внимание статус отчета будет изменен на "Проверенный"</div>
        {% endblock %}
        <form action="/close_report_save/{{object.id}}/" method="post" enctype="multipart/form-data">{% csrf_token %}
        </form>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary" onclick="$('.modal-body > form').submit();">Сохранить</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Отменить</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->

writers/templates/create_sallary.html
{% extends "base.html" %}

{% load staticfiles %}
    {% block custom_script %}
        <script type="text/javascript">
            function calculate() {
                var myBox1 = document.getElementById('id_cost').value; 
                var myBox2 = document.getElementById('id_number_position').value;
                var result = document.getElementById('id_wage'); 
                var myResult = myBox1 * myBox2;
                result.value = myResult;
            }
            </script>
    {% endblock %}

{% block content %}
    <div>
        <form action="." method="post">{% csrf_token %}
            <div class="panel panel-primary">
                <div class="panel-heading"><h3 class="panel-title">Добавить зарплату сотруднику <span class="glyphicon glyphicon-euro"></span></h3></div>
            <div class="panel-body">
                
                <div>
                {{ form.date.errors }}
                {{ form.date.label_tag }}
                {{ form.date }}
                &nbsp;
                {{ form.performer_sallary.errors }}
                {{ form.performer_sallary.label_tag }}
                {{ form.performer_sallary }}
                &nbsp;
                {{ form.name_job.errors }}
                {{ form.name_job.label_tag }}
                {{ form.name_job }}
                </div>
                <hr>
                <p></p>
                <div>
                {{ form.cost.errors }}
                {{ form.cost.label_tag }}
                {{ form.cost }}
                &nbsp;
                {{ form.number_position.errors }}
                {{ form.number_position.label_tag }}
                {{ form.number_position }}
                &nbsp;
                {{ form.wage.errors }}
                {{ form.wage.label_tag }}
                {{ form.wage }}
                </div>
                <p></p>
                <hr>
                <div>
                {{ form.note.errors }}
                {{ form.note.label_tag }}
                {{ form.note }}
                </div>
                
            </div>
        </div>
            <button type="submit" class="btn btn-success">Сохранить</button>
        </form>
        {% include 'autocomplete_light/static.html' %}
    </div>
{% endblock %}

writers/templates/performers.html
{% extends "base.html" %}

{% block content %}
    <a href="/performers/freelancer/">Фрилансеры</a>
    <a href="/performers/office/">Сотрудники в офисе</a>
    <a href="/performers/">Все сотрудники</a>
    <br>
    <h5>{{performer}} <span class="badge">{{list_performers|length}} </span></h5>
     <table class = "table table-striped">
     <thead>
        <tr>
            <th>ФИО</th>
            <th>Ник</th>
            <th>Должность</th>
            <th>Тип сотрудничества</th>
            <th>Номер зарплатной карты</th>
            <th>Имя в skype</th>
            <th>Email</th>
        </tr>
     </thead>
     <tbody>
         {% for obj in list_performers %}
        <tr>
            <td>{{obj.get_full_name}}</td>
            <td>{{obj.username}}</td>
            <td>{{obj.position}}</td>
            <td>{{obj.get_type_performer_display}}</td>
            <td>{{obj.number_cart}}</td>
            <td>{{obj.skype}}</td>
            <td>{{obj.email}}</td>
        </tr>
        {% endfor %}
     </tbody>
     
     </table>
        
{% endblock %}

writers/templates/sallary.html
{% extends "base.html" %}
    {% load staticfiles %}
    {% block custom_script %}
        <script type="text/javascript">
        $(function() {
          $("#test").click(function() {
             $.get("/xhr_test/", function(data) {
                alert(data);
             });
          });
        });
        </script>
    {% endblock %}

{% block content %}
    
<!--
    <input type="button" id="test" value="Display JS Array"/>
-->
    <a href="/sallary/freelancer/">Фрилансеры</a>
    <a href="/sallary/office/">Сотрудники в офисе</a>
    <a href="/sallary/">Все сотрудники</a>
    <h5>{{performer}} <span class="badge">{{sallary_performers|length}} </span></h5>
    <br>
    <a href = "/create_sallary/" class="btn btn-primary">Добавить зарплату</a>
    <br>
    <hr>
     <table class = "table table-striped">
     <thead>
        <tr>
            <th>Дата</th>
            <th>ФИО</th>
            <th>Тип сотрудничества</th>
            <th>Наименование проекта</th>
            <th>Сумма з/п (грн.)</th>
            <th>Прим.</th>
        </tr>
     </thead>
     <tbody>
         {% for obj in sallary_performers %}
        <tr>
            <td>{{obj.date}}</td>
            <td>{{obj.performer_sallary.get_full_name}}</td>
            <td>{{obj.performer_sallary.get_type_performer_display}}</td>
            <td>{{obj.name_job.name}}</td>
            <td>{{obj.wage}}</td>
            <td>{{obj.note}}</td>
        </tr>
        {% endfor %}
     </tbody>
     
     </table>
        
{% endblock %}